version: '3.8'
services:

    app:
        build: .
        image: letgo-php
        container_name: app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: webserver
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
